// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "practice/golang/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// WorkerRepository is an autogenerated mock type for the WorkerRepository type
type WorkerRepository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *WorkerRepository) GetAll() (domain.WorkerResponse, error) {
	ret := _m.Called()

	var r0 domain.WorkerResponse
	if rf, ok := ret.Get(0).(func() domain.WorkerResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.WorkerResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
