version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./script/init_db.sql:/init.sql
  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: backend
    volumes:
      - .:/go/src/backend
    ports:
      - "9999:9999"
    security_opt:
      - "seccomp:unconfined"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: front-end
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run serve
    depends_on:
      - backend
    networks:
      - backend
volumes:
  my-db:
networks:
  backend:
    driver: bridge
